import Head from "next/head";
import Link from "next/link";
import styled from "@emotion/styled";

export default function Home() {
  return (
    <>
      <Head>
        <title>Main Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavBar>
        <NavItem>
          <Link href="/fortunedog">Fortune Dog</Link>
        </NavItem>
        <NavItem>
          <Link href="/calculator">Calculator</Link>
        </NavItem>
      </NavBar>

      <MainContent>
        <h1>Hello, World!</h1>
        <p>Welcome to the main page. Choose a page from the menu above.</p>
      </MainContent>
    </>
  );
}

// 스타일 정의
const NavBar = styled.nav`
  display: flex;
  justify-content: center;
  background-color: #007aff;
  padding: 16px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 0;
  z-index: 10;

  @media (max-width: 480px) {
    padding: 12px;
  }
`;

const NavItem = styled.div`
  margin: 0 20px;
  font-size: 1.2em;

  a {
    color: white;
    text-decoration: none;
    font-weight: bold;
    transition: color 0.2s;

    &:hover {
      color: #005bb5;
    }
  }

  @media (max-width: 480px) {
    font-size: 1em;
    margin: 0 12px;
  }
`;

const MainContent = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px 20px;
  text-align: center;

  @media (max-width: 480px) {
    padding: 20px 10px;
  }

  h1 {
    font-size: 2em;
    margin-bottom: 20px;
  }

  p {
    font-size: 1em;
    color: #6e6e73;
  }
`;
